[27/Jun/2021 07:42:52] INFO [django.utils.autoreload:636] Watching for file changes with StatReloader
[29/Jun/2021 04:17:02] INFO [django.utils.autoreload:636] Watching for file changes with StatReloader
[29/Jun/2021 04:17:05] INFO [django.server:161] "GET /admin/toy_auth/user/ HTTP/1.1" 302 0
[29/Jun/2021 04:17:05] INFO [django.server:161] "GET /admin/login/?next=/admin/toy_auth/user/ HTTP/1.1" 200 2242
[29/Jun/2021 04:17:05] INFO [django.server:161] "GET /static/admin/css/nav_sidebar.css HTTP/1.1" 200 2271
[29/Jun/2021 04:17:05] INFO [django.server:161] "GET /static/admin/css/base.css HTTP/1.1" 200 19513
[29/Jun/2021 04:17:05] INFO [django.server:161] "GET /static/admin/css/login.css HTTP/1.1" 200 939
[29/Jun/2021 04:17:05] INFO [django.server:161] "GET /static/admin/css/responsive.css HTTP/1.1" 200 18545
[29/Jun/2021 04:17:05] INFO [django.server:161] "GET /static/admin/js/nav_sidebar.js HTTP/1.1" 200 1360
[29/Jun/2021 04:17:05] INFO [django.server:161] "GET /static/admin/css/fonts.css HTTP/1.1" 200 423
[29/Jun/2021 04:17:05] INFO [django.server:161] "GET /static/admin/fonts/Roboto-Light-webfont.woff HTTP/1.1" 200 85692
[29/Jun/2021 04:17:05] INFO [django.server:161] "GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1" 200 85876
[29/Jun/2021 04:17:13] INFO [django.server:161] "POST /admin/login/?next=/admin/toy_auth/user/ HTTP/1.1" 302 0
[29/Jun/2021 04:17:14] ERROR [django.request:224] Internal Server Error: /admin/toy_auth/user/
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/contrib/admin/utils.py", line 319, in label_for_field
    field = _get_non_gfk_field(model._meta, name)
  File "/usr/local/lib/python3.9/site-packages/django/contrib/admin/utils.py", line 300, in _get_non_gfk_field
    raise FieldDoesNotExist()
django.core.exceptions.FieldDoesNotExist

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 204, in _get_response
    response = response.render()
  File "/usr/local/lib/python3.9/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/usr/local/lib/python3.9/site-packages/django/template/response.py", line 83, in rendered_content
    return template.render(context, self._request)
  File "/usr/local/lib/python3.9/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 170, in render
    return self._render(context)
  File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.9/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.9/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.9/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.9/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.9/site-packages/django/contrib/admin/templatetags/base.py", line 33, in render
    return super().render(context)
  File "/usr/local/lib/python3.9/site-packages/django/template/library.py", line 214, in render
    _dict = self.func(*resolved_args, **resolved_kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/contrib/admin/templatetags/admin_list.py", line 298, in result_list
    headers = list(result_headers(cl))
  File "/usr/local/lib/python3.9/site-packages/django/contrib/admin/templatetags/admin_list.py", line 79, in result_headers
    text, attr = label_for_field(
  File "/usr/local/lib/python3.9/site-packages/django/contrib/admin/utils.py", line 344, in label_for_field
    raise AttributeError(message)
AttributeError: Unable to lookup 'room' on User or UserAdmin
[29/Jun/2021 04:17:14] ERROR [django.server:161] "GET /admin/toy_auth/user/ HTTP/1.1" 500 297769
[29/Jun/2021 04:17:33] INFO [django.utils.autoreload:250] /workspace/toy_auth/admin.py changed, reloading.
[29/Jun/2021 04:17:35] INFO [django.utils.autoreload:636] Watching for file changes with StatReloader
[29/Jun/2021 04:17:39] ERROR [django.request:224] Internal Server Error: /admin/toy_auth/user/
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/contrib/admin/utils.py", line 319, in label_for_field
    field = _get_non_gfk_field(model._meta, name)
  File "/usr/local/lib/python3.9/site-packages/django/contrib/admin/utils.py", line 300, in _get_non_gfk_field
    raise FieldDoesNotExist()
django.core.exceptions.FieldDoesNotExist

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 204, in _get_response
    response = response.render()
  File "/usr/local/lib/python3.9/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/usr/local/lib/python3.9/site-packages/django/template/response.py", line 83, in rendered_content
    return template.render(context, self._request)
  File "/usr/local/lib/python3.9/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 170, in render
    return self._render(context)
  File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.9/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.9/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.9/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.9/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.9/site-packages/django/contrib/admin/templatetags/base.py", line 33, in render
    return super().render(context)
  File "/usr/local/lib/python3.9/site-packages/django/template/library.py", line 214, in render
    _dict = self.func(*resolved_args, **resolved_kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/contrib/admin/templatetags/admin_list.py", line 298, in result_list
    headers = list(result_headers(cl))
  File "/usr/local/lib/python3.9/site-packages/django/contrib/admin/templatetags/admin_list.py", line 79, in result_headers
    text, attr = label_for_field(
  File "/usr/local/lib/python3.9/site-packages/django/contrib/admin/utils.py", line 344, in label_for_field
    raise AttributeError(message)
AttributeError: Unable to lookup 'room' on User or UserAdmin
[29/Jun/2021 04:17:39] ERROR [django.server:161] "GET /admin/toy_auth/user/ HTTP/1.1" 500 297769
[29/Jun/2021 04:17:41] ERROR [django.request:224] Internal Server Error: /admin/toy_auth/user/
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/contrib/admin/utils.py", line 319, in label_for_field
    field = _get_non_gfk_field(model._meta, name)
  File "/usr/local/lib/python3.9/site-packages/django/contrib/admin/utils.py", line 300, in _get_non_gfk_field
    raise FieldDoesNotExist()
django.core.exceptions.FieldDoesNotExist

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 204, in _get_response
    response = response.render()
  File "/usr/local/lib/python3.9/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/usr/local/lib/python3.9/site-packages/django/template/response.py", line 83, in rendered_content
    return template.render(context, self._request)
  File "/usr/local/lib/python3.9/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 170, in render
    return self._render(context)
  File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.9/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.9/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.9/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.9/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.9/site-packages/django/contrib/admin/templatetags/base.py", line 33, in render
    return super().render(context)
  File "/usr/local/lib/python3.9/site-packages/django/template/library.py", line 214, in render
    _dict = self.func(*resolved_args, **resolved_kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/contrib/admin/templatetags/admin_list.py", line 298, in result_list
    headers = list(result_headers(cl))
  File "/usr/local/lib/python3.9/site-packages/django/contrib/admin/templatetags/admin_list.py", line 79, in result_headers
    text, attr = label_for_field(
  File "/usr/local/lib/python3.9/site-packages/django/contrib/admin/utils.py", line 344, in label_for_field
    raise AttributeError(message)
AttributeError: Unable to lookup 'room' on User or UserAdmin
[29/Jun/2021 04:17:41] ERROR [django.server:161] "GET /admin/toy_auth/user/ HTTP/1.1" 500 297769
[29/Jun/2021 04:19:10] INFO [django.utils.autoreload:250] /workspace/toy_auth/admin.py changed, reloading.
[29/Jun/2021 04:19:13] INFO [django.utils.autoreload:636] Watching for file changes with StatReloader
[29/Jun/2021 04:19:20] INFO [django.server:161] "GET /admin/toy_auth/user/ HTTP/1.1" 200 22840
[29/Jun/2021 04:19:20] INFO [django.server:161] "GET /static/admin/css/changelists.css HTTP/1.1" 200 6874
[29/Jun/2021 04:19:20] INFO [django.server:161] "GET /static/admin/js/core.js HTTP/1.1" 200 5698
[29/Jun/2021 04:19:20] INFO [django.server:161] "GET /static/admin/js/jquery.init.js HTTP/1.1" 200 347
[29/Jun/2021 04:19:20] INFO [django.server:161] "GET /static/admin/js/actions.js HTTP/1.1" 200 7664
[29/Jun/2021 04:19:20] INFO [django.server:161] "GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 200 5984
[29/Jun/2021 04:19:20] INFO [django.server:161] "GET /admin/jsi18n/ HTTP/1.1" 200 3195
[29/Jun/2021 04:19:20] INFO [django.server:161] "GET /static/admin/js/prepopulate.js HTTP/1.1" 200 1531
[29/Jun/2021 04:19:20] INFO [django.server:161] "GET /static/admin/js/urlify.js HTTP/1.1" 200 7902
[29/Jun/2021 04:19:20] INFO [django.server:161] "GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 200 232381
[29/Jun/2021 04:19:20] INFO [django.server:161] "GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 200 287630
[29/Jun/2021 04:19:20] INFO [django.server:161] "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 200 331
[29/Jun/2021 04:19:20] INFO [django.server:161] "GET /static/admin/img/tooltag-add.svg HTTP/1.1" 200 331
[29/Jun/2021 04:19:20] INFO [django.server:161] "GET /static/admin/img/sorting-icons.svg HTTP/1.1" 200 1097
[29/Jun/2021 04:19:20] INFO [django.server:161] "GET /static/admin/fonts/Roboto-Bold-webfont.woff HTTP/1.1" 200 86184
